package com.rtmap.apistore.task.entity;

import java.util.Date;

public class TaskFollow {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_follow.TASK_ID
     *
     * @mbggenerated Wed Mar 23 22:15:36 CST 2016
     */
    private String taskId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_follow.FOLLOWER
     *
     * @mbggenerated Wed Mar 23 22:15:36 CST 2016
     */
    private String follower;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_follow.FOLLOW_TIME
     *
     * @mbggenerated Wed Mar 23 22:15:36 CST 2016
     */
    private Date followTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_follow.TASK_ID
     *
     * @return the value of task_follow.TASK_ID
     *
     * @mbggenerated Wed Mar 23 22:15:36 CST 2016
     */
    public String getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_follow.TASK_ID
     *
     * @param taskId the value for task_follow.TASK_ID
     *
     * @mbggenerated Wed Mar 23 22:15:36 CST 2016
     */
    public void setTaskId(String taskId) {
        this.taskId = taskId == null ? null : taskId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_follow.FOLLOWER
     *
     * @return the value of task_follow.FOLLOWER
     *
     * @mbggenerated Wed Mar 23 22:15:36 CST 2016
     */
    public String getFollower() {
        return follower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_follow.FOLLOWER
     *
     * @param follower the value for task_follow.FOLLOWER
     *
     * @mbggenerated Wed Mar 23 22:15:36 CST 2016
     */
    public void setFollower(String follower) {
        this.follower = follower == null ? null : follower.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_follow.FOLLOW_TIME
     *
     * @return the value of task_follow.FOLLOW_TIME
     *
     * @mbggenerated Wed Mar 23 22:15:36 CST 2016
     */
    public Date getFollowTime() {
        return followTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_follow.FOLLOW_TIME
     *
     * @param followTime the value for task_follow.FOLLOW_TIME
     *
     * @mbggenerated Wed Mar 23 22:15:36 CST 2016
     */
    public void setFollowTime(Date followTime) {
        this.followTime = followTime;
    }
}