package com.rtmap.apistore.task.entity;

import java.util.Date;

public class TaskRemind {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_remind.REMIND_ID
     *
     * @mbggenerated Wed Mar 23 22:16:36 CST 2016
     */
    private String remindId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_remind.TASK_ID
     *
     * @mbggenerated Wed Mar 23 22:16:36 CST 2016
     */
    private String taskId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_remind.REMIND_CONT
     *
     * @mbggenerated Wed Mar 23 22:16:36 CST 2016
     */
    private String remindCont;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_remind.REMIND_USER
     *
     * @mbggenerated Wed Mar 23 22:16:36 CST 2016
     */
    private String remindUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_remind.REMIND_HANDLER
     *
     * @mbggenerated Wed Mar 23 22:16:36 CST 2016
     */
    private String remindHandler;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_remind.REMIND_MODE
     *
     * @mbggenerated Wed Mar 23 22:16:36 CST 2016
     */
    private String remindMode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_remind.REMIND_TYPE
     *
     * @mbggenerated Wed Mar 23 22:16:36 CST 2016
     */
    private Short remindType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_remind.RECORD_TIME
     *
     * @mbggenerated Wed Mar 23 22:16:36 CST 2016
     */
    private Date recordTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_remind.REMIND_ID
     *
     * @return the value of task_remind.REMIND_ID
     *
     * @mbggenerated Wed Mar 23 22:16:36 CST 2016
     */
    public String getRemindId() {
        return remindId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_remind.REMIND_ID
     *
     * @param remindId the value for task_remind.REMIND_ID
     *
     * @mbggenerated Wed Mar 23 22:16:36 CST 2016
     */
    public void setRemindId(String remindId) {
        this.remindId = remindId == null ? null : remindId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_remind.TASK_ID
     *
     * @return the value of task_remind.TASK_ID
     *
     * @mbggenerated Wed Mar 23 22:16:36 CST 2016
     */
    public String getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_remind.TASK_ID
     *
     * @param taskId the value for task_remind.TASK_ID
     *
     * @mbggenerated Wed Mar 23 22:16:36 CST 2016
     */
    public void setTaskId(String taskId) {
        this.taskId = taskId == null ? null : taskId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_remind.REMIND_CONT
     *
     * @return the value of task_remind.REMIND_CONT
     *
     * @mbggenerated Wed Mar 23 22:16:36 CST 2016
     */
    public String getRemindCont() {
        return remindCont;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_remind.REMIND_CONT
     *
     * @param remindCont the value for task_remind.REMIND_CONT
     *
     * @mbggenerated Wed Mar 23 22:16:36 CST 2016
     */
    public void setRemindCont(String remindCont) {
        this.remindCont = remindCont == null ? null : remindCont.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_remind.REMIND_USER
     *
     * @return the value of task_remind.REMIND_USER
     *
     * @mbggenerated Wed Mar 23 22:16:36 CST 2016
     */
    public String getRemindUser() {
        return remindUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_remind.REMIND_USER
     *
     * @param remindUser the value for task_remind.REMIND_USER
     *
     * @mbggenerated Wed Mar 23 22:16:36 CST 2016
     */
    public void setRemindUser(String remindUser) {
        this.remindUser = remindUser == null ? null : remindUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_remind.REMIND_HANDLER
     *
     * @return the value of task_remind.REMIND_HANDLER
     *
     * @mbggenerated Wed Mar 23 22:16:36 CST 2016
     */
    public String getRemindHandler() {
        return remindHandler;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_remind.REMIND_HANDLER
     *
     * @param remindHandler the value for task_remind.REMIND_HANDLER
     *
     * @mbggenerated Wed Mar 23 22:16:36 CST 2016
     */
    public void setRemindHandler(String remindHandler) {
        this.remindHandler = remindHandler == null ? null : remindHandler.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_remind.REMIND_MODE
     *
     * @return the value of task_remind.REMIND_MODE
     *
     * @mbggenerated Wed Mar 23 22:16:36 CST 2016
     */
    public String getRemindMode() {
        return remindMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_remind.REMIND_MODE
     *
     * @param remindMode the value for task_remind.REMIND_MODE
     *
     * @mbggenerated Wed Mar 23 22:16:36 CST 2016
     */
    public void setRemindMode(String remindMode) {
        this.remindMode = remindMode == null ? null : remindMode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_remind.REMIND_TYPE
     *
     * @return the value of task_remind.REMIND_TYPE
     *
     * @mbggenerated Wed Mar 23 22:16:36 CST 2016
     */
    public Short getRemindType() {
        return remindType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_remind.REMIND_TYPE
     *
     * @param remindType the value for task_remind.REMIND_TYPE
     *
     * @mbggenerated Wed Mar 23 22:16:36 CST 2016
     */
    public void setRemindType(Short remindType) {
        this.remindType = remindType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_remind.RECORD_TIME
     *
     * @return the value of task_remind.RECORD_TIME
     *
     * @mbggenerated Wed Mar 23 22:16:36 CST 2016
     */
    public Date getRecordTime() {
        return recordTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_remind.RECORD_TIME
     *
     * @param recordTime the value for task_remind.RECORD_TIME
     *
     * @mbggenerated Wed Mar 23 22:16:36 CST 2016
     */
    public void setRecordTime(Date recordTime) {
        this.recordTime = recordTime;
    }
}