package com.rtmap.apistore.task.entity;

import java.util.Date;

public class TaskLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_log.LOG_ID
     *
     * @mbggenerated Wed Mar 23 22:15:54 CST 2016
     */
    private String logId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_log.TASK_ID
     *
     * @mbggenerated Wed Mar 23 22:15:54 CST 2016
     */
    private String taskId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_log.OPERATE_TYPE
     *
     * @mbggenerated Wed Mar 23 22:15:54 CST 2016
     */
    private Short operateType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_log.OPERATE_CONT
     *
     * @mbggenerated Wed Mar 23 22:15:54 CST 2016
     */
    private String operateCont;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_log.OPERATOR
     *
     * @mbggenerated Wed Mar 23 22:15:54 CST 2016
     */
    private String operator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_log.OPERATE_TIME
     *
     * @mbggenerated Wed Mar 23 22:15:54 CST 2016
     */
    private Date operateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_log.LOG_ID
     *
     * @return the value of task_log.LOG_ID
     *
     * @mbggenerated Wed Mar 23 22:15:54 CST 2016
     */
    public String getLogId() {
        return logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_log.LOG_ID
     *
     * @param logId the value for task_log.LOG_ID
     *
     * @mbggenerated Wed Mar 23 22:15:54 CST 2016
     */
    public void setLogId(String logId) {
        this.logId = logId == null ? null : logId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_log.TASK_ID
     *
     * @return the value of task_log.TASK_ID
     *
     * @mbggenerated Wed Mar 23 22:15:54 CST 2016
     */
    public String getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_log.TASK_ID
     *
     * @param taskId the value for task_log.TASK_ID
     *
     * @mbggenerated Wed Mar 23 22:15:54 CST 2016
     */
    public void setTaskId(String taskId) {
        this.taskId = taskId == null ? null : taskId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_log.OPERATE_TYPE
     *
     * @return the value of task_log.OPERATE_TYPE
     *
     * @mbggenerated Wed Mar 23 22:15:54 CST 2016
     */
    public Short getOperateType() {
        return operateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_log.OPERATE_TYPE
     *
     * @param operateType the value for task_log.OPERATE_TYPE
     *
     * @mbggenerated Wed Mar 23 22:15:54 CST 2016
     */
    public void setOperateType(Short operateType) {
        this.operateType = operateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_log.OPERATE_CONT
     *
     * @return the value of task_log.OPERATE_CONT
     *
     * @mbggenerated Wed Mar 23 22:15:54 CST 2016
     */
    public String getOperateCont() {
        return operateCont;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_log.OPERATE_CONT
     *
     * @param operateCont the value for task_log.OPERATE_CONT
     *
     * @mbggenerated Wed Mar 23 22:15:54 CST 2016
     */
    public void setOperateCont(String operateCont) {
        this.operateCont = operateCont == null ? null : operateCont.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_log.OPERATOR
     *
     * @return the value of task_log.OPERATOR
     *
     * @mbggenerated Wed Mar 23 22:15:54 CST 2016
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_log.OPERATOR
     *
     * @param operator the value for task_log.OPERATOR
     *
     * @mbggenerated Wed Mar 23 22:15:54 CST 2016
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_log.OPERATE_TIME
     *
     * @return the value of task_log.OPERATE_TIME
     *
     * @mbggenerated Wed Mar 23 22:15:54 CST 2016
     */
    public Date getOperateTime() {
        return operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_log.OPERATE_TIME
     *
     * @param operateTime the value for task_log.OPERATE_TIME
     *
     * @mbggenerated Wed Mar 23 22:15:54 CST 2016
     */
    public void setOperateTime(Date operateTime) {
        this.operateTime = operateTime;
    }
}