package com.rtmap.apistore.task.entity;

import java.util.Date;

public class TaskFlow {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_flow.FLOW_ID
     *
     * @mbggenerated Wed Mar 23 22:14:26 CST 2016
     */
    private String flowId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_flow.TASK_ID
     *
     * @mbggenerated Wed Mar 23 22:14:26 CST 2016
     */
    private String taskId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_flow.TAS_ASSIGNER
     *
     * @mbggenerated Wed Mar 23 22:14:26 CST 2016
     */
    private String tasAssigner;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_flow.TASK_HANDLER
     *
     * @mbggenerated Wed Mar 23 22:14:26 CST 2016
     */
    private String taskHandler;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_flow.ASSIGN_TIME
     *
     * @mbggenerated Wed Mar 23 22:14:26 CST 2016
     */
    private Date assignTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_flow.FLOW_ID
     *
     * @return the value of task_flow.FLOW_ID
     *
     * @mbggenerated Wed Mar 23 22:14:26 CST 2016
     */
    public String getFlowId() {
        return flowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_flow.FLOW_ID
     *
     * @param flowId the value for task_flow.FLOW_ID
     *
     * @mbggenerated Wed Mar 23 22:14:26 CST 2016
     */
    public void setFlowId(String flowId) {
        this.flowId = flowId == null ? null : flowId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_flow.TASK_ID
     *
     * @return the value of task_flow.TASK_ID
     *
     * @mbggenerated Wed Mar 23 22:14:26 CST 2016
     */
    public String getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_flow.TASK_ID
     *
     * @param taskId the value for task_flow.TASK_ID
     *
     * @mbggenerated Wed Mar 23 22:14:26 CST 2016
     */
    public void setTaskId(String taskId) {
        this.taskId = taskId == null ? null : taskId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_flow.TAS_ASSIGNER
     *
     * @return the value of task_flow.TAS_ASSIGNER
     *
     * @mbggenerated Wed Mar 23 22:14:26 CST 2016
     */
    public String getTasAssigner() {
        return tasAssigner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_flow.TAS_ASSIGNER
     *
     * @param tasAssigner the value for task_flow.TAS_ASSIGNER
     *
     * @mbggenerated Wed Mar 23 22:14:26 CST 2016
     */
    public void setTasAssigner(String tasAssigner) {
        this.tasAssigner = tasAssigner == null ? null : tasAssigner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_flow.TASK_HANDLER
     *
     * @return the value of task_flow.TASK_HANDLER
     *
     * @mbggenerated Wed Mar 23 22:14:26 CST 2016
     */
    public String getTaskHandler() {
        return taskHandler;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_flow.TASK_HANDLER
     *
     * @param taskHandler the value for task_flow.TASK_HANDLER
     *
     * @mbggenerated Wed Mar 23 22:14:26 CST 2016
     */
    public void setTaskHandler(String taskHandler) {
        this.taskHandler = taskHandler == null ? null : taskHandler.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_flow.ASSIGN_TIME
     *
     * @return the value of task_flow.ASSIGN_TIME
     *
     * @mbggenerated Wed Mar 23 22:14:26 CST 2016
     */
    public Date getAssignTime() {
        return assignTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_flow.ASSIGN_TIME
     *
     * @param assignTime the value for task_flow.ASSIGN_TIME
     *
     * @mbggenerated Wed Mar 23 22:14:26 CST 2016
     */
    public void setAssignTime(Date assignTime) {
        this.assignTime = assignTime;
    }
}