package com.rtmap.apistore.task.entity;

import java.util.Date;

public class TaskParticipant {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_participant.TASK_ID
     *
     * @mbggenerated Wed Mar 23 22:16:14 CST 2016
     */
    private String taskId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_participant.PARTICIPANT
     *
     * @mbggenerated Wed Mar 23 22:16:14 CST 2016
     */
    private String participant;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_participant.OPERATOR
     *
     * @mbggenerated Wed Mar 23 22:16:14 CST 2016
     */
    private String operator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_participant.OPERATE_TIME
     *
     * @mbggenerated Wed Mar 23 22:16:14 CST 2016
     */
    private Date operateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_participant.TASK_ID
     *
     * @return the value of task_participant.TASK_ID
     *
     * @mbggenerated Wed Mar 23 22:16:14 CST 2016
     */
    public String getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_participant.TASK_ID
     *
     * @param taskId the value for task_participant.TASK_ID
     *
     * @mbggenerated Wed Mar 23 22:16:14 CST 2016
     */
    public void setTaskId(String taskId) {
        this.taskId = taskId == null ? null : taskId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_participant.PARTICIPANT
     *
     * @return the value of task_participant.PARTICIPANT
     *
     * @mbggenerated Wed Mar 23 22:16:14 CST 2016
     */
    public String getParticipant() {
        return participant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_participant.PARTICIPANT
     *
     * @param participant the value for task_participant.PARTICIPANT
     *
     * @mbggenerated Wed Mar 23 22:16:14 CST 2016
     */
    public void setParticipant(String participant) {
        this.participant = participant == null ? null : participant.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_participant.OPERATOR
     *
     * @return the value of task_participant.OPERATOR
     *
     * @mbggenerated Wed Mar 23 22:16:14 CST 2016
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_participant.OPERATOR
     *
     * @param operator the value for task_participant.OPERATOR
     *
     * @mbggenerated Wed Mar 23 22:16:14 CST 2016
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_participant.OPERATE_TIME
     *
     * @return the value of task_participant.OPERATE_TIME
     *
     * @mbggenerated Wed Mar 23 22:16:14 CST 2016
     */
    public Date getOperateTime() {
        return operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_participant.OPERATE_TIME
     *
     * @param operateTime the value for task_participant.OPERATE_TIME
     *
     * @mbggenerated Wed Mar 23 22:16:14 CST 2016
     */
    public void setOperateTime(Date operateTime) {
        this.operateTime = operateTime;
    }
}