package com.rtmap.apistore.task.entity;

import java.util.Date;

public class TaskAttachFile {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_attach_file.ATTACH_ID
     *
     * @mbggenerated Wed Mar 23 22:14:56 CST 2016
     */
    private String attachId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_attach_file.TASK_ID
     *
     * @mbggenerated Wed Mar 23 22:14:56 CST 2016
     */
    private String taskId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_attach_file.ATTACH_NAME
     *
     * @mbggenerated Wed Mar 23 22:14:56 CST 2016
     */
    private String attachName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_attach_file.ATTACH_PATH
     *
     * @mbggenerated Wed Mar 23 22:14:56 CST 2016
     */
    private String attachPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_attach_file.OPERATOR
     *
     * @mbggenerated Wed Mar 23 22:14:56 CST 2016
     */
    private String operator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_attach_file.OPERATE_TIME
     *
     * @mbggenerated Wed Mar 23 22:14:56 CST 2016
     */
    private Date operateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_attach_file.ATTACH_ID
     *
     * @return the value of task_attach_file.ATTACH_ID
     *
     * @mbggenerated Wed Mar 23 22:14:56 CST 2016
     */
    public String getAttachId() {
        return attachId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_attach_file.ATTACH_ID
     *
     * @param attachId the value for task_attach_file.ATTACH_ID
     *
     * @mbggenerated Wed Mar 23 22:14:56 CST 2016
     */
    public void setAttachId(String attachId) {
        this.attachId = attachId == null ? null : attachId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_attach_file.TASK_ID
     *
     * @return the value of task_attach_file.TASK_ID
     *
     * @mbggenerated Wed Mar 23 22:14:56 CST 2016
     */
    public String getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_attach_file.TASK_ID
     *
     * @param taskId the value for task_attach_file.TASK_ID
     *
     * @mbggenerated Wed Mar 23 22:14:56 CST 2016
     */
    public void setTaskId(String taskId) {
        this.taskId = taskId == null ? null : taskId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_attach_file.ATTACH_NAME
     *
     * @return the value of task_attach_file.ATTACH_NAME
     *
     * @mbggenerated Wed Mar 23 22:14:56 CST 2016
     */
    public String getAttachName() {
        return attachName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_attach_file.ATTACH_NAME
     *
     * @param attachName the value for task_attach_file.ATTACH_NAME
     *
     * @mbggenerated Wed Mar 23 22:14:56 CST 2016
     */
    public void setAttachName(String attachName) {
        this.attachName = attachName == null ? null : attachName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_attach_file.ATTACH_PATH
     *
     * @return the value of task_attach_file.ATTACH_PATH
     *
     * @mbggenerated Wed Mar 23 22:14:56 CST 2016
     */
    public String getAttachPath() {
        return attachPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_attach_file.ATTACH_PATH
     *
     * @param attachPath the value for task_attach_file.ATTACH_PATH
     *
     * @mbggenerated Wed Mar 23 22:14:56 CST 2016
     */
    public void setAttachPath(String attachPath) {
        this.attachPath = attachPath == null ? null : attachPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_attach_file.OPERATOR
     *
     * @return the value of task_attach_file.OPERATOR
     *
     * @mbggenerated Wed Mar 23 22:14:56 CST 2016
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_attach_file.OPERATOR
     *
     * @param operator the value for task_attach_file.OPERATOR
     *
     * @mbggenerated Wed Mar 23 22:14:56 CST 2016
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_attach_file.OPERATE_TIME
     *
     * @return the value of task_attach_file.OPERATE_TIME
     *
     * @mbggenerated Wed Mar 23 22:14:56 CST 2016
     */
    public Date getOperateTime() {
        return operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_attach_file.OPERATE_TIME
     *
     * @param operateTime the value for task_attach_file.OPERATE_TIME
     *
     * @mbggenerated Wed Mar 23 22:14:56 CST 2016
     */
    public void setOperateTime(Date operateTime) {
        this.operateTime = operateTime;
    }
}