package com.rtmap.apistore.task.entity;

import java.util.Date;

public class TaskComment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_comment.COMMENT_ID
     *
     * @mbggenerated Wed Mar 23 22:15:17 CST 2016
     */
    private String commentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_comment.TASK_ID
     *
     * @mbggenerated Wed Mar 23 22:15:17 CST 2016
     */
    private String taskId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_comment.FLOW_ID
     *
     * @mbggenerated Wed Mar 23 22:15:17 CST 2016
     */
    private String flowId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_comment.REPLY_TYPE
     *
     * @mbggenerated Wed Mar 23 22:15:17 CST 2016
     */
    private Short replyType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_comment.COMMENTS
     *
     * @mbggenerated Wed Mar 23 22:15:17 CST 2016
     */
    private String comments;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_comment.REPLIER
     *
     * @mbggenerated Wed Mar 23 22:15:17 CST 2016
     */
    private String replier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_comment.REPLY_TIME
     *
     * @mbggenerated Wed Mar 23 22:15:17 CST 2016
     */
    private Date replyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_comment.COMMENT_ID
     *
     * @return the value of task_comment.COMMENT_ID
     *
     * @mbggenerated Wed Mar 23 22:15:17 CST 2016
     */
    public String getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_comment.COMMENT_ID
     *
     * @param commentId the value for task_comment.COMMENT_ID
     *
     * @mbggenerated Wed Mar 23 22:15:17 CST 2016
     */
    public void setCommentId(String commentId) {
        this.commentId = commentId == null ? null : commentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_comment.TASK_ID
     *
     * @return the value of task_comment.TASK_ID
     *
     * @mbggenerated Wed Mar 23 22:15:17 CST 2016
     */
    public String getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_comment.TASK_ID
     *
     * @param taskId the value for task_comment.TASK_ID
     *
     * @mbggenerated Wed Mar 23 22:15:17 CST 2016
     */
    public void setTaskId(String taskId) {
        this.taskId = taskId == null ? null : taskId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_comment.FLOW_ID
     *
     * @return the value of task_comment.FLOW_ID
     *
     * @mbggenerated Wed Mar 23 22:15:17 CST 2016
     */
    public String getFlowId() {
        return flowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_comment.FLOW_ID
     *
     * @param flowId the value for task_comment.FLOW_ID
     *
     * @mbggenerated Wed Mar 23 22:15:17 CST 2016
     */
    public void setFlowId(String flowId) {
        this.flowId = flowId == null ? null : flowId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_comment.REPLY_TYPE
     *
     * @return the value of task_comment.REPLY_TYPE
     *
     * @mbggenerated Wed Mar 23 22:15:17 CST 2016
     */
    public Short getReplyType() {
        return replyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_comment.REPLY_TYPE
     *
     * @param replyType the value for task_comment.REPLY_TYPE
     *
     * @mbggenerated Wed Mar 23 22:15:17 CST 2016
     */
    public void setReplyType(Short replyType) {
        this.replyType = replyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_comment.COMMENTS
     *
     * @return the value of task_comment.COMMENTS
     *
     * @mbggenerated Wed Mar 23 22:15:17 CST 2016
     */
    public String getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_comment.COMMENTS
     *
     * @param comments the value for task_comment.COMMENTS
     *
     * @mbggenerated Wed Mar 23 22:15:17 CST 2016
     */
    public void setComments(String comments) {
        this.comments = comments == null ? null : comments.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_comment.REPLIER
     *
     * @return the value of task_comment.REPLIER
     *
     * @mbggenerated Wed Mar 23 22:15:17 CST 2016
     */
    public String getReplier() {
        return replier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_comment.REPLIER
     *
     * @param replier the value for task_comment.REPLIER
     *
     * @mbggenerated Wed Mar 23 22:15:17 CST 2016
     */
    public void setReplier(String replier) {
        this.replier = replier == null ? null : replier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_comment.REPLY_TIME
     *
     * @return the value of task_comment.REPLY_TIME
     *
     * @mbggenerated Wed Mar 23 22:15:17 CST 2016
     */
    public Date getReplyTime() {
        return replyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_comment.REPLY_TIME
     *
     * @param replyTime the value for task_comment.REPLY_TIME
     *
     * @mbggenerated Wed Mar 23 22:15:17 CST 2016
     */
    public void setReplyTime(Date replyTime) {
        this.replyTime = replyTime;
    }
}