package com.rtmap.apistore.task.entity;

import java.util.Date;

public class TaskInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_info.TASK_ID
     *
     * @mbggenerated Wed Mar 23 22:09:40 CST 2016
     */
    private String taskId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_info.TASK_NAME
     *
     * @mbggenerated Wed Mar 23 22:09:40 CST 2016
     */
    private String taskName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_info.TASK_CONT
     *
     * @mbggenerated Wed Mar 23 22:09:40 CST 2016
     */
    private String taskCont;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_info.TASK_STATUS
     *
     * @mbggenerated Wed Mar 23 22:09:40 CST 2016
     */
    private Short taskStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_info.TASK _TYPE
     *
     * @mbggenerated Wed Mar 23 22:09:40 CST 2016
     */
    private Short taskType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_info.TASK_PRIORITY
     *
     * @mbggenerated Wed Mar 23 22:09:40 CST 2016
     */
    private Short taskPriority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_info.TASK_RELATE
     *
     * @mbggenerated Wed Mar 23 22:09:40 CST 2016
     */
    private String taskRelate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_info.TASK_RELATE_JSON
     *
     * @mbggenerated Wed Mar 23 22:09:40 CST 2016
     */
    private String taskRelateJson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_info.TASK_PID
     *
     * @mbggenerated Wed Mar 23 22:09:40 CST 2016
     */
    private String taskPid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_info.BEGIN_DATE
     *
     * @mbggenerated Wed Mar 23 22:09:40 CST 2016
     */
    private Date beginDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_info.DEADLINE
     *
     * @mbggenerated Wed Mar 23 22:09:40 CST 2016
     */
    private Date deadline;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_info.REMIND_MODE
     *
     * @mbggenerated Wed Mar 23 22:09:40 CST 2016
     */
    private String remindMode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_info.REMIND_MEMBER
     *
     * @mbggenerated Wed Mar 23 22:09:40 CST 2016
     */
    private String remindMember;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_info.REMIND_EXPIRE_DAYS
     *
     * @mbggenerated Wed Mar 23 22:09:40 CST 2016
     */
    private Short remindExpireDays;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_info.CREATOR
     *
     * @mbggenerated Wed Mar 23 22:09:40 CST 2016
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_info.CREATE_TIME
     *
     * @mbggenerated Wed Mar 23 22:09:40 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_info.MODIFIER
     *
     * @mbggenerated Wed Mar 23 22:09:40 CST 2016
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_info.MODIFY_TIME
     *
     * @mbggenerated Wed Mar 23 22:09:40 CST 2016
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_info.LFT
     *
     * @mbggenerated Wed Mar 23 22:09:40 CST 2016
     */
    private Integer lft;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_info.RGT
     *
     * @mbggenerated Wed Mar 23 22:09:40 CST 2016
     */
    private Integer rgt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_info.TASK_ID
     *
     * @return the value of task_info.TASK_ID
     *
     * @mbggenerated Wed Mar 23 22:09:40 CST 2016
     */
    public String getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_info.TASK_ID
     *
     * @param taskId the value for task_info.TASK_ID
     *
     * @mbggenerated Wed Mar 23 22:09:40 CST 2016
     */
    public void setTaskId(String taskId) {
        this.taskId = taskId == null ? null : taskId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_info.TASK_NAME
     *
     * @return the value of task_info.TASK_NAME
     *
     * @mbggenerated Wed Mar 23 22:09:40 CST 2016
     */
    public String getTaskName() {
        return taskName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_info.TASK_NAME
     *
     * @param taskName the value for task_info.TASK_NAME
     *
     * @mbggenerated Wed Mar 23 22:09:40 CST 2016
     */
    public void setTaskName(String taskName) {
        this.taskName = taskName == null ? null : taskName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_info.TASK_CONT
     *
     * @return the value of task_info.TASK_CONT
     *
     * @mbggenerated Wed Mar 23 22:09:40 CST 2016
     */
    public String getTaskCont() {
        return taskCont;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_info.TASK_CONT
     *
     * @param taskCont the value for task_info.TASK_CONT
     *
     * @mbggenerated Wed Mar 23 22:09:40 CST 2016
     */
    public void setTaskCont(String taskCont) {
        this.taskCont = taskCont == null ? null : taskCont.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_info.TASK_STATUS
     *
     * @return the value of task_info.TASK_STATUS
     *
     * @mbggenerated Wed Mar 23 22:09:40 CST 2016
     */
    public Short getTaskStatus() {
        return taskStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_info.TASK_STATUS
     *
     * @param taskStatus the value for task_info.TASK_STATUS
     *
     * @mbggenerated Wed Mar 23 22:09:40 CST 2016
     */
    public void setTaskStatus(Short taskStatus) {
        this.taskStatus = taskStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_info.TASK _TYPE
     *
     * @return the value of task_info.TASK _TYPE
     *
     * @mbggenerated Wed Mar 23 22:09:40 CST 2016
     */
    public Short getTaskType() {
        return taskType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_info.TASK _TYPE
     *
     * @param taskType the value for task_info.TASK _TYPE
     *
     * @mbggenerated Wed Mar 23 22:09:40 CST 2016
     */
    public void setTaskType(Short taskType) {
        this.taskType = taskType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_info.TASK_PRIORITY
     *
     * @return the value of task_info.TASK_PRIORITY
     *
     * @mbggenerated Wed Mar 23 22:09:40 CST 2016
     */
    public Short getTaskPriority() {
        return taskPriority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_info.TASK_PRIORITY
     *
     * @param taskPriority the value for task_info.TASK_PRIORITY
     *
     * @mbggenerated Wed Mar 23 22:09:40 CST 2016
     */
    public void setTaskPriority(Short taskPriority) {
        this.taskPriority = taskPriority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_info.TASK_RELATE
     *
     * @return the value of task_info.TASK_RELATE
     *
     * @mbggenerated Wed Mar 23 22:09:40 CST 2016
     */
    public String getTaskRelate() {
        return taskRelate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_info.TASK_RELATE
     *
     * @param taskRelate the value for task_info.TASK_RELATE
     *
     * @mbggenerated Wed Mar 23 22:09:40 CST 2016
     */
    public void setTaskRelate(String taskRelate) {
        this.taskRelate = taskRelate == null ? null : taskRelate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_info.TASK_RELATE_JSON
     *
     * @return the value of task_info.TASK_RELATE_JSON
     *
     * @mbggenerated Wed Mar 23 22:09:40 CST 2016
     */
    public String getTaskRelateJson() {
        return taskRelateJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_info.TASK_RELATE_JSON
     *
     * @param taskRelateJson the value for task_info.TASK_RELATE_JSON
     *
     * @mbggenerated Wed Mar 23 22:09:40 CST 2016
     */
    public void setTaskRelateJson(String taskRelateJson) {
        this.taskRelateJson = taskRelateJson == null ? null : taskRelateJson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_info.TASK_PID
     *
     * @return the value of task_info.TASK_PID
     *
     * @mbggenerated Wed Mar 23 22:09:40 CST 2016
     */
    public String getTaskPid() {
        return taskPid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_info.TASK_PID
     *
     * @param taskPid the value for task_info.TASK_PID
     *
     * @mbggenerated Wed Mar 23 22:09:40 CST 2016
     */
    public void setTaskPid(String taskPid) {
        this.taskPid = taskPid == null ? null : taskPid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_info.BEGIN_DATE
     *
     * @return the value of task_info.BEGIN_DATE
     *
     * @mbggenerated Wed Mar 23 22:09:40 CST 2016
     */
    public Date getBeginDate() {
        return beginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_info.BEGIN_DATE
     *
     * @param beginDate the value for task_info.BEGIN_DATE
     *
     * @mbggenerated Wed Mar 23 22:09:40 CST 2016
     */
    public void setBeginDate(Date beginDate) {
        this.beginDate = beginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_info.DEADLINE
     *
     * @return the value of task_info.DEADLINE
     *
     * @mbggenerated Wed Mar 23 22:09:40 CST 2016
     */
    public Date getDeadline() {
        return deadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_info.DEADLINE
     *
     * @param deadline the value for task_info.DEADLINE
     *
     * @mbggenerated Wed Mar 23 22:09:40 CST 2016
     */
    public void setDeadline(Date deadline) {
        this.deadline = deadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_info.REMIND_MODE
     *
     * @return the value of task_info.REMIND_MODE
     *
     * @mbggenerated Wed Mar 23 22:09:40 CST 2016
     */
    public String getRemindMode() {
        return remindMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_info.REMIND_MODE
     *
     * @param remindMode the value for task_info.REMIND_MODE
     *
     * @mbggenerated Wed Mar 23 22:09:40 CST 2016
     */
    public void setRemindMode(String remindMode) {
        this.remindMode = remindMode == null ? null : remindMode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_info.REMIND_MEMBER
     *
     * @return the value of task_info.REMIND_MEMBER
     *
     * @mbggenerated Wed Mar 23 22:09:40 CST 2016
     */
    public String getRemindMember() {
        return remindMember;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_info.REMIND_MEMBER
     *
     * @param remindMember the value for task_info.REMIND_MEMBER
     *
     * @mbggenerated Wed Mar 23 22:09:40 CST 2016
     */
    public void setRemindMember(String remindMember) {
        this.remindMember = remindMember == null ? null : remindMember.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_info.REMIND_EXPIRE_DAYS
     *
     * @return the value of task_info.REMIND_EXPIRE_DAYS
     *
     * @mbggenerated Wed Mar 23 22:09:40 CST 2016
     */
    public Short getRemindExpireDays() {
        return remindExpireDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_info.REMIND_EXPIRE_DAYS
     *
     * @param remindExpireDays the value for task_info.REMIND_EXPIRE_DAYS
     *
     * @mbggenerated Wed Mar 23 22:09:40 CST 2016
     */
    public void setRemindExpireDays(Short remindExpireDays) {
        this.remindExpireDays = remindExpireDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_info.CREATOR
     *
     * @return the value of task_info.CREATOR
     *
     * @mbggenerated Wed Mar 23 22:09:40 CST 2016
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_info.CREATOR
     *
     * @param creator the value for task_info.CREATOR
     *
     * @mbggenerated Wed Mar 23 22:09:40 CST 2016
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_info.CREATE_TIME
     *
     * @return the value of task_info.CREATE_TIME
     *
     * @mbggenerated Wed Mar 23 22:09:40 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_info.CREATE_TIME
     *
     * @param createTime the value for task_info.CREATE_TIME
     *
     * @mbggenerated Wed Mar 23 22:09:40 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_info.MODIFIER
     *
     * @return the value of task_info.MODIFIER
     *
     * @mbggenerated Wed Mar 23 22:09:40 CST 2016
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_info.MODIFIER
     *
     * @param modifier the value for task_info.MODIFIER
     *
     * @mbggenerated Wed Mar 23 22:09:40 CST 2016
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_info.MODIFY_TIME
     *
     * @return the value of task_info.MODIFY_TIME
     *
     * @mbggenerated Wed Mar 23 22:09:40 CST 2016
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_info.MODIFY_TIME
     *
     * @param modifyTime the value for task_info.MODIFY_TIME
     *
     * @mbggenerated Wed Mar 23 22:09:40 CST 2016
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_info.LFT
     *
     * @return the value of task_info.LFT
     *
     * @mbggenerated Wed Mar 23 22:09:40 CST 2016
     */
    public Integer getLft() {
        return lft;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_info.LFT
     *
     * @param lft the value for task_info.LFT
     *
     * @mbggenerated Wed Mar 23 22:09:40 CST 2016
     */
    public void setLft(Integer lft) {
        this.lft = lft;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_info.RGT
     *
     * @return the value of task_info.RGT
     *
     * @mbggenerated Wed Mar 23 22:09:40 CST 2016
     */
    public Integer getRgt() {
        return rgt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_info.RGT
     *
     * @param rgt the value for task_info.RGT
     *
     * @mbggenerated Wed Mar 23 22:09:40 CST 2016
     */
    public void setRgt(Integer rgt) {
        this.rgt = rgt;
    }
}