package com.rtmap.apistore.task.dao;

import com.rtmap.apistore.task.entity.TaskFlow;

public interface TaskFlowDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_flow
     *
     * @mbggenerated Wed Mar 23 22:14:26 CST 2016
     */
    int deleteByPrimaryKey(String flowId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_flow
     *
     * @mbggenerated Wed Mar 23 22:14:26 CST 2016
     */
    int insert(TaskFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_flow
     *
     * @mbggenerated Wed Mar 23 22:14:26 CST 2016
     */
    int insertSelective(TaskFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_flow
     *
     * @mbggenerated Wed Mar 23 22:14:26 CST 2016
     */
    TaskFlow selectByPrimaryKey(String flowId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_flow
     *
     * @mbggenerated Wed Mar 23 22:14:26 CST 2016
     */
    int updateByPrimaryKeySelective(TaskFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_flow
     *
     * @mbggenerated Wed Mar 23 22:14:26 CST 2016
     */
    int updateByPrimaryKey(TaskFlow record);
}