package com.rtmap.apistore.task.dao;

import com.rtmap.apistore.task.entity.TaskParticipant;

public interface TaskParticipantDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_participant
     *
     * @mbggenerated Wed Mar 23 22:16:14 CST 2016
     */
    int deleteByPrimaryKey(String taskId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_participant
     *
     * @mbggenerated Wed Mar 23 22:16:14 CST 2016
     */
    int insert(TaskParticipant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_participant
     *
     * @mbggenerated Wed Mar 23 22:16:14 CST 2016
     */
    int insertSelective(TaskParticipant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_participant
     *
     * @mbggenerated Wed Mar 23 22:16:14 CST 2016
     */
    TaskParticipant selectByPrimaryKey(String taskId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_participant
     *
     * @mbggenerated Wed Mar 23 22:16:14 CST 2016
     */
    int updateByPrimaryKeySelective(TaskParticipant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_participant
     *
     * @mbggenerated Wed Mar 23 22:16:14 CST 2016
     */
    int updateByPrimaryKey(TaskParticipant record);
}