package com.rtmap.apistore.task.dao;

import com.rtmap.apistore.task.entity.TaskFollow;

public interface TaskFollowDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_follow
     *
     * @mbggenerated Wed Mar 23 22:15:36 CST 2016
     */
    int deleteByPrimaryKey(String taskId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_follow
     *
     * @mbggenerated Wed Mar 23 22:15:36 CST 2016
     */
    int insert(TaskFollow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_follow
     *
     * @mbggenerated Wed Mar 23 22:15:36 CST 2016
     */
    int insertSelective(TaskFollow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_follow
     *
     * @mbggenerated Wed Mar 23 22:15:36 CST 2016
     */
    TaskFollow selectByPrimaryKey(String taskId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_follow
     *
     * @mbggenerated Wed Mar 23 22:15:36 CST 2016
     */
    int updateByPrimaryKeySelective(TaskFollow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_follow
     *
     * @mbggenerated Wed Mar 23 22:15:36 CST 2016
     */
    int updateByPrimaryKey(TaskFollow record);
}