package com.rtmap.apistore.task.dao;

import com.rtmap.apistore.task.entity.TaskLog;

public interface TaskLogDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_log
     *
     * @mbggenerated Wed Mar 23 22:15:54 CST 2016
     */
    int deleteByPrimaryKey(String logId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_log
     *
     * @mbggenerated Wed Mar 23 22:15:54 CST 2016
     */
    int insert(TaskLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_log
     *
     * @mbggenerated Wed Mar 23 22:15:54 CST 2016
     */
    int insertSelective(TaskLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_log
     *
     * @mbggenerated Wed Mar 23 22:15:54 CST 2016
     */
    TaskLog selectByPrimaryKey(String logId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_log
     *
     * @mbggenerated Wed Mar 23 22:15:54 CST 2016
     */
    int updateByPrimaryKeySelective(TaskLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_log
     *
     * @mbggenerated Wed Mar 23 22:15:54 CST 2016
     */
    int updateByPrimaryKey(TaskLog record);
}