package com.rtmap.apistore.task.dao;

import com.rtmap.apistore.task.entity.TaskInfo;

public interface TaskInfoDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_info
     *
     * @mbggenerated Wed Mar 23 22:10:30 CST 2016
     */
    int deleteByPrimaryKey(String taskId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_info
     *
     * @mbggenerated Wed Mar 23 22:10:30 CST 2016
     */
    int insert(TaskInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_info
     *
     * @mbggenerated Wed Mar 23 22:10:30 CST 2016
     */
    int insertSelective(TaskInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_info
     *
     * @mbggenerated Wed Mar 23 22:10:30 CST 2016
     */
    TaskInfo selectByPrimaryKey(String taskId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_info
     *
     * @mbggenerated Wed Mar 23 22:10:30 CST 2016
     */
    int updateByPrimaryKeySelective(TaskInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_info
     *
     * @mbggenerated Wed Mar 23 22:10:30 CST 2016
     */
    int updateByPrimaryKey(TaskInfo record);
}