package com.rtmap.apistore.task.dao;

import com.rtmap.apistore.task.entity.TaskComment;

public interface TaskCommentDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_comment
     *
     * @mbggenerated Wed Mar 23 22:15:17 CST 2016
     */
    int deleteByPrimaryKey(String commentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_comment
     *
     * @mbggenerated Wed Mar 23 22:15:17 CST 2016
     */
    int insert(TaskComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_comment
     *
     * @mbggenerated Wed Mar 23 22:15:17 CST 2016
     */
    int insertSelective(TaskComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_comment
     *
     * @mbggenerated Wed Mar 23 22:15:17 CST 2016
     */
    TaskComment selectByPrimaryKey(String commentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_comment
     *
     * @mbggenerated Wed Mar 23 22:15:17 CST 2016
     */
    int updateByPrimaryKeySelective(TaskComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_comment
     *
     * @mbggenerated Wed Mar 23 22:15:17 CST 2016
     */
    int updateByPrimaryKey(TaskComment record);
}