package com.rtmap.apistore.task.dao;

import com.rtmap.apistore.task.entity.TaskRemindLog;

public interface TaskRemindLogDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_remind_log
     *
     * @mbggenerated Wed Mar 23 22:17:40 CST 2016
     */
    int deleteByPrimaryKey(String remindId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_remind_log
     *
     * @mbggenerated Wed Mar 23 22:17:40 CST 2016
     */
    int insert(TaskRemindLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_remind_log
     *
     * @mbggenerated Wed Mar 23 22:17:40 CST 2016
     */
    int insertSelective(TaskRemindLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_remind_log
     *
     * @mbggenerated Wed Mar 23 22:17:40 CST 2016
     */
    TaskRemindLog selectByPrimaryKey(String remindId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_remind_log
     *
     * @mbggenerated Wed Mar 23 22:17:40 CST 2016
     */
    int updateByPrimaryKeySelective(TaskRemindLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_remind_log
     *
     * @mbggenerated Wed Mar 23 22:17:40 CST 2016
     */
    int updateByPrimaryKey(TaskRemindLog record);
}