package com.rtmap.apistore.task.dao;

import com.rtmap.apistore.task.entity.TaskAttachFile;

public interface TaskAttachFileDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_attach_file
     *
     * @mbggenerated Wed Mar 23 22:14:56 CST 2016
     */
    int deleteByPrimaryKey(String attachId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_attach_file
     *
     * @mbggenerated Wed Mar 23 22:14:56 CST 2016
     */
    int insert(TaskAttachFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_attach_file
     *
     * @mbggenerated Wed Mar 23 22:14:56 CST 2016
     */
    int insertSelective(TaskAttachFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_attach_file
     *
     * @mbggenerated Wed Mar 23 22:14:56 CST 2016
     */
    TaskAttachFile selectByPrimaryKey(String attachId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_attach_file
     *
     * @mbggenerated Wed Mar 23 22:14:56 CST 2016
     */
    int updateByPrimaryKeySelective(TaskAttachFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_attach_file
     *
     * @mbggenerated Wed Mar 23 22:14:56 CST 2016
     */
    int updateByPrimaryKey(TaskAttachFile record);
}